import type {
  Customer,
  Complaint,
  ClusterData,
  AtRiskCustomer,
  PredictiveAlert,
  ComplianceDeadline,
  ComplianceReport,
  ResponseTemplate,
  KnowledgeArticle,
} from "./types";

export const customers: Customer[] = [
  {
    id: "CUST-001",
    name: "Priya Mehta",
    initials: "PM",
    email: "priya.mehta@email.com",
    phone: "+91 98765 43210",
    segment: "Premium",
    accountNumber: "XXXX-XXXX-4521",
    joinedDate: "2019-03-15",
    totalComplaints: 3,
    resolvedComplaints: 2,
    riskScore: 45,
  },
  {
    id: "CUST-002",
    name: "Amit Kumar",
    initials: "AK",
    email: "amit.kumar@email.com",
    phone: "+91 98765 43211",
    segment: "Gold",
    accountNumber: "XXXX-XXXX-7823",
    joinedDate: "2020-07-22",
    totalComplaints: 2,
    resolvedComplaints: 1,
    riskScore: 32,
  },
  {
    id: "CUST-003",
    name: "Sneha Reddy",
    initials: "SR",
    email: "sneha.reddy@email.com",
    phone: "+91 98765 43212",
    segment: "Premium",
    accountNumber: "XXXX-XXXX-9102",
    joinedDate: "2018-11-08",
    totalComplaints: 5,
    resolvedComplaints: 4,
    riskScore: 58,
  },
  {
    id: "CUST-004",
    name: "Rajesh Patel",
    initials: "RP",
    email: "rajesh.patel@email.com",
    phone: "+91 98765 43213",
    segment: "Silver",
    accountNumber: "XXXX-XXXX-3456",
    joinedDate: "2021-02-14",
    totalComplaints: 1,
    resolvedComplaints: 0,
    riskScore: 22,
  },
  {
    id: "CUST-005",
    name: "Kavitha Nair",
    initials: "KN",
    email: "kavitha.nair@email.com",
    phone: "+91 98765 43214",
    segment: "Gold",
    accountNumber: "XXXX-XXXX-6789",
    joinedDate: "2019-09-30",
    totalComplaints: 4,
    resolvedComplaints: 3,
    riskScore: 41,
  },
];

export const complaints: Complaint[] = [
  {
    id: "CMP-2847",
    customerId: "CUST-001",
    customer: customers[0],
    category: "Transaction Issues",
    subCategory: "UPI Payment",
    summary: "Failed UPI transaction but amount debited",
    description:
      "UPI payment of Rs. 15,000 to beneficiary account failed but amount has been debited from my account. Transaction ID: UPI/2847/MARCH/2026. The transaction was initiated at 2:30 PM today. I need immediate resolution as this was an urgent payment for medical expenses.",
    priority: "high",
    status: "in-progress",
    channel: "mobile-app",
    createdAt: "2026-03-22T15:45:00",
    updatedAt: "2026-03-22T15:52:00",
    slaDeadline: "2026-03-22T23:45:00",
    assignedTo: "Rahul Sharma",
    amount: 15000,
    transactionId: "UPI/2847/MARCH/2026",
    messages: [
      {
        id: "MSG-001",
        sender: "customer",
        senderName: "Priya Mehta",
        senderInitials: "PM",
        content: "Please help! My UPI payment failed but money was deducted. This is very urgent.",
        timestamp: "2026-03-22T15:45:00",
      },
      {
        id: "MSG-002",
        sender: "agent",
        senderName: "Rahul Sharma",
        senderInitials: "RS",
        content:
          "Dear Ms. Mehta, I understand your concern regarding the failed UPI transaction. I have initiated an immediate investigation on transaction ID UPI/2847/MARCH/2026. I am checking with our payment gateway team for the status.",
        timestamp: "2026-03-22T15:52:00",
      },
    ],
    attachments: [
      {
        id: "ATT-001",
        name: "transaction_screenshot.png",
        type: "image/png",
        size: "245 KB",
        url: "#",
      },
    ],
  },
  {
    id: "CMP-2846",
    customerId: "CUST-002",
    customer: customers[1],
    category: "Account Services",
    subCategory: "KYC Update",
    summary: "Unable to update KYC documents online",
    description:
      "I have been trying to update my Aadhaar-linked KYC through the mobile app for the past 3 days but keep getting an error message. My account services are being restricted due to pending KYC.",
    priority: "medium",
    status: "in-progress",
    channel: "mobile-app",
    createdAt: "2026-03-22T11:30:00",
    updatedAt: "2026-03-22T12:15:00",
    slaDeadline: "2026-03-23T11:30:00",
    assignedTo: "Priya Verma",
    messages: [
      {
        id: "MSG-003",
        sender: "customer",
        senderName: "Amit Kumar",
        senderInitials: "AK",
        content: "I cannot update my KYC. The app shows technical error every time.",
        timestamp: "2026-03-22T11:30:00",
      },
    ],
    attachments: [],
  },
  {
    id: "CMP-2845",
    customerId: "CUST-003",
    customer: customers[2],
    category: "Loan & Credit",
    subCategory: "EMI Calculation",
    summary: "Incorrect interest rate applied on home loan EMI",
    description:
      "My home loan EMI has increased by Rs. 2,500 this month without any prior notice. The interest rate applied seems to be 0.5% higher than my sanctioned rate. Loan account: HL-98765.",
    priority: "high",
    status: "escalated",
    channel: "branch",
    createdAt: "2026-03-22T10:15:00",
    updatedAt: "2026-03-22T14:30:00",
    slaDeadline: "2026-03-22T18:15:00",
    assignedTo: "Vikram Singh",
    amount: 2500,
    messages: [
      {
        id: "MSG-004",
        sender: "customer",
        senderName: "Sneha Reddy",
        senderInitials: "SR",
        content: "Why has my EMI increased? I was not informed about any rate change.",
        timestamp: "2026-03-22T10:15:00",
      },
      {
        id: "MSG-005",
        sender: "agent",
        senderName: "Vikram Singh",
        senderInitials: "VS",
        content: "I am escalating this to our loan processing team for immediate review.",
        timestamp: "2026-03-22T14:30:00",
      },
    ],
    attachments: [],
  },
  {
    id: "CMP-2844",
    customerId: "CUST-004",
    customer: customers[3],
    category: "Digital Banking",
    subCategory: "App Issues",
    summary: "Mobile app crashes during bill payment",
    description:
      "The mobile banking app crashes every time I try to pay my electricity bill. I have already missed the due date because of this issue.",
    priority: "low",
    status: "open",
    channel: "email",
    createdAt: "2026-03-22T09:45:00",
    updatedAt: "2026-03-22T09:45:00",
    slaDeadline: "2026-03-23T09:45:00",
    assignedTo: "Unassigned",
    messages: [],
    attachments: [],
  },
  {
    id: "CMP-2843",
    customerId: "CUST-005",
    customer: customers[4],
    category: "Transaction Issues",
    subCategory: "ATM Transaction",
    summary: "Duplicate debit for single ATM withdrawal",
    description:
      "I withdrew Rs. 10,000 from ATM but my account was debited twice. Both debits show at 4:32 PM. ATM ID: ATM-MUM-0234.",
    priority: "high",
    status: "in-progress",
    channel: "call-center",
    createdAt: "2026-03-22T08:00:00",
    updatedAt: "2026-03-22T10:30:00",
    slaDeadline: "2026-03-22T16:00:00",
    assignedTo: "Rahul Sharma",
    amount: 10000,
    messages: [
      {
        id: "MSG-006",
        sender: "customer",
        senderName: "Kavitha Nair",
        senderInitials: "KN",
        content: "Double debit has happened for my ATM withdrawal!",
        timestamp: "2026-03-22T08:00:00",
      },
    ],
    attachments: [],
  },
];

export const clusters: ClusterData[] = [
  {
    id: 1,
    name: "UPI Failures",
    count: 156,
    x: 20,
    y: 25,
    size: 80,
    color: "bg-chart-1",
    category: "Transaction",
    keywords: ["failed", "upi", "timeout", "pending", "debit"],
    trend: "increasing",
    affectedChannels: ["mobile-app", "web"],
    rootCauses: [
      "NPCI gateway timeout during peak hours",
      "Bank server response delays",
      "Network connectivity issues on customer side",
    ],
    recommendations: [
      "Implement automatic retry mechanism for timeout cases",
      "Add real-time NPCI status indicator in app",
      "Pre-authorize smaller transactions to reduce load",
    ],
  },
  {
    id: 2,
    name: "ATM Issues",
    count: 89,
    x: 55,
    y: 20,
    size: 60,
    color: "bg-chart-2",
    category: "Account",
    keywords: ["atm", "withdrawal", "stuck", "duplicate", "cash"],
    trend: "stable",
    affectedChannels: ["call-center", "branch"],
    rootCauses: [
      "Cash dispenser mechanical failures",
      "Network connectivity issues with ATMs",
      "ATM software glitches during transactions",
    ],
    recommendations: [
      "Increase preventive maintenance frequency",
      "Implement automatic reversal for stuck transactions",
      "Add SMS confirmation for successful dispensing",
    ],
  },
  {
    id: 3,
    name: "Card Declined",
    count: 124,
    x: 75,
    y: 45,
    size: 70,
    color: "bg-chart-3",
    category: "Cards",
    keywords: ["declined", "card", "blocked", "limit", "international"],
    trend: "decreasing",
    affectedChannels: ["call-center", "mobile-app"],
    rootCauses: [
      "Fraud detection false positives",
      "International transaction blocks",
      "Daily limit exceeded without notification",
    ],
    recommendations: [
      "Improve ML model for fraud detection accuracy",
      "Send proactive alerts before limit breach",
      "Simplify international enable/disable toggle",
    ],
  },
  {
    id: 4,
    name: "App Crashes",
    count: 67,
    x: 30,
    y: 60,
    size: 50,
    color: "bg-chart-4",
    category: "Digital",
    keywords: ["crash", "app", "freeze", "error", "login"],
    trend: "increasing",
    affectedChannels: ["mobile-app"],
    rootCauses: [
      "Memory leak in payment module (v3.2.1)",
      "Incompatibility with Android 14 on some devices",
      "Session timeout handling bug",
    ],
    recommendations: [
      "Priority fix for payment module memory leak",
      "Add device-specific testing for Android 14",
      "Implement graceful session recovery",
    ],
  },
  {
    id: 5,
    name: "KYC Delays",
    count: 45,
    x: 60,
    y: 70,
    size: 40,
    color: "bg-chart-5",
    category: "Loans",
    keywords: ["kyc", "aadhaar", "verification", "pending", "documents"],
    trend: "stable",
    affectedChannels: ["mobile-app", "branch"],
    rootCauses: [
      "UIDAI server response delays",
      "Document OCR failures for poor quality images",
      "Manual verification backlog",
    ],
    recommendations: [
      "Add image quality checker before submission",
      "Implement video KYC as alternative",
      "Increase auto-verification coverage",
    ],
  },
  {
    id: 6,
    name: "EMI Errors",
    count: 78,
    x: 15,
    y: 80,
    size: 55,
    color: "bg-chart-1",
    category: "Transaction",
    keywords: ["emi", "interest", "calculation", "deduction", "prepayment"],
    trend: "increasing",
    affectedChannels: ["branch", "email"],
    rootCauses: [
      "Interest rate update sync issues",
      "Prepayment calculation errors",
      "System not reflecting RBI rate changes",
    ],
    recommendations: [
      "Audit interest rate sync mechanism",
      "Send detailed EMI breakdown proactively",
      "Auto-notify customers of rate changes",
    ],
  },
];

export const atRiskCustomers: AtRiskCustomer[] = [
  {
    id: "CUST-101",
    name: "Vikram Malhotra",
    initials: "VM",
    segment: "Premium",
    riskScore: 92,
    signals: [
      { type: "transaction", description: "3 failed transactions", severity: "high" },
      { type: "sentiment", description: "Negative call sentiment", severity: "high" },
    ],
    lastContact: "2 days ago",
    predictedIssue: "Account closure intent",
    recommendedAction: "Priority callback from relationship manager",
    contacted: false,
  },
  {
    id: "CUST-102",
    name: "Ananya Sharma",
    initials: "AS",
    segment: "Gold",
    riskScore: 87,
    signals: [
      { type: "payment", description: "EMI bounce", severity: "high" },
      { type: "support", description: "Multiple support calls", severity: "medium" },
    ],
    lastContact: "1 day ago",
    predictedIssue: "Payment dispute",
    recommendedAction: "Offer payment restructuring options",
    contacted: false,
  },
  {
    id: "CUST-103",
    name: "Mohammed Rashid",
    initials: "MR",
    segment: "Premium",
    riskScore: 84,
    signals: [
      { type: "card", description: "Card blocked", severity: "high" },
      { type: "branch", description: "Branch visit pending", severity: "medium" },
    ],
    lastContact: "3 days ago",
    predictedIssue: "Card services complaint",
    recommendedAction: "Proactive card replacement offer",
    contacted: true,
  },
  {
    id: "CUST-104",
    name: "Deepa Krishnan",
    initials: "DK",
    segment: "Regular",
    riskScore: 78,
    signals: [
      { type: "app", description: "App crash reports", severity: "medium" },
      { type: "login", description: "Login failures", severity: "medium" },
    ],
    lastContact: "5 days ago",
    predictedIssue: "Technical support needed",
    recommendedAction: "Send troubleshooting guide + offer callback",
    contacted: false,
  },
  {
    id: "CUST-105",
    name: "Arjun Patel",
    initials: "AP",
    segment: "Gold",
    riskScore: 75,
    signals: [
      { type: "query", description: "Interest rate query", severity: "low" },
      { type: "loan", description: "Loan prepayment inquiry", severity: "medium" },
    ],
    lastContact: "1 week ago",
    predictedIssue: "Loan refinancing",
    recommendedAction: "Share competitive retention offer",
    contacted: false,
  },
];

export const predictiveAlerts: PredictiveAlert[] = [
  {
    id: "ALERT-001",
    title: "UPI Failure Spike Expected",
    description:
      "Based on historical patterns and current NPCI load, 23% increase in UPI failure complaints expected in the next 4 hours.",
    severity: "critical",
    category: "Transaction Issues",
    affectedCustomers: 450,
    predictedComplaints: 45,
    confidence: 89,
    recommendedAction: "Pre-emptively notify customers about potential delays. Prepare support team for increased volume.",
    dismissed: false,
    createdAt: "2026-03-22T14:00:00",
  },
  {
    id: "ALERT-002",
    title: "EMI Deduction Day Surge",
    description:
      "5th of month approaching. Typically 34% increase in EMI-related queries. 12 customers have insufficient balance.",
    severity: "high",
    category: "Loan & Credit",
    affectedCustomers: 12,
    predictedComplaints: 8,
    confidence: 94,
    recommendedAction: "Send balance reminder to 12 at-risk customers. Schedule extra staff for support.",
    dismissed: false,
    createdAt: "2026-03-22T12:00:00",
  },
  {
    id: "ALERT-003",
    title: "Mobile App Update Issues",
    description:
      "New app version (v3.2.1) showing 15% higher crash rate. Affecting Android 14 users primarily.",
    severity: "medium",
    category: "Digital Banking",
    affectedCustomers: 230,
    predictedComplaints: 25,
    confidence: 78,
    recommendedAction: "Consider rollback or hotfix. Prepare FAQs for support team.",
    dismissed: false,
    createdAt: "2026-03-22T10:00:00",
  },
];

export const complianceDeadlines: ComplianceDeadline[] = [
  {
    id: "DL-001",
    complaintId: "CMP-2843",
    customerName: "Kavitha Nair",
    category: "Transaction Issues",
    deadline: "2026-03-22T16:00:00",
    hoursRemaining: 2,
    status: "at-risk",
    assignedTo: "Rahul Sharma",
  },
  {
    id: "DL-002",
    complaintId: "CMP-2845",
    customerName: "Sneha Reddy",
    category: "Loan & Credit",
    deadline: "2026-03-22T18:15:00",
    hoursRemaining: 4,
    status: "at-risk",
    assignedTo: "Vikram Singh",
  },
  {
    id: "DL-003",
    complaintId: "CMP-2847",
    customerName: "Priya Mehta",
    category: "Transaction Issues",
    deadline: "2026-03-22T23:45:00",
    hoursRemaining: 8,
    status: "on-track",
    assignedTo: "Rahul Sharma",
  },
  {
    id: "DL-004",
    complaintId: "CMP-2846",
    customerName: "Amit Kumar",
    category: "Account Services",
    deadline: "2026-03-23T11:30:00",
    hoursRemaining: 20,
    status: "on-track",
    assignedTo: "Priya Verma",
  },
];

export const complianceReports: ComplianceReport[] = [
  {
    id: "RPT-001",
    name: "Monthly Complaint Analysis - March 2026",
    type: "RBI",
    period: "March 2026",
    status: "pending-review",
    dueDate: "2026-04-07",
    downloadUrl: "#",
  },
  {
    id: "RPT-002",
    name: "Quarterly TAT Compliance Report - Q1 2026",
    type: "RBI",
    period: "Q1 2026",
    status: "draft",
    dueDate: "2026-04-15",
    downloadUrl: "#",
  },
  {
    id: "RPT-003",
    name: "Customer Grievance Summary - February 2026",
    type: "RBI",
    period: "February 2026",
    status: "submitted",
    dueDate: "2026-03-07",
    submittedDate: "2026-03-05",
    downloadUrl: "#",
  },
  {
    id: "RPT-004",
    name: "Branch-wise Resolution Metrics",
    type: "Internal",
    period: "March 2026",
    status: "approved",
    dueDate: "2026-03-20",
    submittedDate: "2026-03-18",
    downloadUrl: "#",
  },
];

export const responseTemplates: ResponseTemplate[] = [
  {
    id: "TPL-001",
    name: "UPI Refund Initiated",
    category: "Transaction Issues",
    content:
      "Dear {customer_name}, We have initiated a refund for your failed UPI transaction (Ref: {transaction_id}). The amount of Rs. {amount} will be credited to your account within 2-3 working days. We apologize for the inconvenience caused.",
    usageCount: 245,
  },
  {
    id: "TPL-002",
    name: "KYC Update Assistance",
    category: "Account Services",
    content:
      "Dear {customer_name}, We understand you are facing issues with KYC update. Please try the following: 1) Ensure your Aadhaar is linked to your mobile number, 2) Use a well-lit area for photo capture, 3) Clear app cache and retry. If the issue persists, please visit your nearest branch with original documents.",
    usageCount: 189,
  },
  {
    id: "TPL-003",
    name: "EMI Clarification",
    category: "Loan & Credit",
    content:
      "Dear {customer_name}, Thank you for reaching out regarding your EMI concern. Your current EMI is calculated based on the floating interest rate linked to repo rate. As per RBI guidelines, the rate has been revised. Please find the detailed breakdown attached. For any queries, please contact your relationship manager.",
    usageCount: 156,
  },
  {
    id: "TPL-004",
    name: "App Issue Acknowledgment",
    category: "Digital Banking",
    content:
      "Dear {customer_name}, We apologize for the inconvenience caused by the app issue. Our technical team is aware of this problem and working on a fix. In the meantime, you can use our web banking portal at netbanking.bank.com or visit your nearest branch. We will notify you once the issue is resolved.",
    usageCount: 98,
  },
];

export const knowledgeArticles: KnowledgeArticle[] = [
  {
    id: "KB-001",
    title: "UPI Transaction Failure - Resolution SOP",
    category: "Transaction Issues",
    content: "Step-by-step process for handling UPI transaction failures including timeout scenarios, NPCI escalation procedures, and refund timelines.",
    relevanceScore: 95,
  },
  {
    id: "KB-002",
    title: "RBI Guidelines on Customer Grievance Redressal",
    category: "Compliance",
    content: "Complete guide on RBI circular dated 2024 regarding customer complaint TAT, escalation matrix, and reporting requirements.",
    relevanceScore: 88,
  },
  {
    id: "KB-003",
    title: "ATM Dispute Resolution Process",
    category: "Transaction Issues",
    content: "Detailed process for handling ATM-related complaints including failed withdrawals, duplicate debits, and cash not dispensed scenarios.",
    relevanceScore: 82,
  },
];

export const trendData = [
  { date: "Mar 1", complaints: 85, resolved: 72 },
  { date: "Mar 4", complaints: 92, resolved: 78 },
  { date: "Mar 7", complaints: 78, resolved: 69 },
  { date: "Mar 10", complaints: 105, resolved: 85 },
  { date: "Mar 13", complaints: 95, resolved: 82 },
  { date: "Mar 16", complaints: 112, resolved: 95 },
  { date: "Mar 19", complaints: 88, resolved: 76 },
  { date: "Mar 22", complaints: 98, resolved: 71 },
];

export const categoryData = [
  { name: "Transaction", value: 35, color: "var(--chart-1)" },
  { name: "Account", value: 22, color: "var(--chart-2)" },
  { name: "Loans", value: 18, color: "var(--chart-3)" },
  { name: "Cards", value: 15, color: "var(--chart-4)" },
  { name: "Digital", value: 10, color: "var(--chart-5)" },
];
